// Generated by Wrangler on Sat Jul 27 2024 20:58:43 GMT+0800 (China Standard Time)
// by running `wrangler types`

interface Env {
        kv: KVNamespace;
        CaptchaSecretKey: string;
        DB: D1Database;
        logdb: AnalyticsEngineDataset;
        AI: Ai;
        NOTIFICATION_SERVICE: Fetcher;
}
