name = "xmoj-bbs"
main = "Source/index.ts"
compatibility_date = "2023-09-17"
account_id = "89969bdf9d5ab8202f8ad8b8ae2c40b8"
kv_namespaces = [
    { binding = "kv", id = "05ecbc2affef4f7b99359ea88422f53e", preview_id = "ca2f99e1c80546cab855a472147f835a"}
]

[[d1_databases]]
binding = "DB"
database_name = "xmoj-bbs"
database_id = "952d0135-a7b0-4eb7-9a1f-e529d6e7b479"

[triggers]
crons = ["0 0 * * *"]

[[analytics_engine_datasets]]
binding = "logdb"

[ai]
binding = "AI"

[observability]
enabled = true
