name = "xmoj-bbs"
main = "Source/index.ts"
compatibility_date = "2023-09-17"
account_id = "89969bdf9d5ab8202f8ad8b8ae2c40b8"

[[d1_databases]]
binding = "DB"
database_name = "xmoj-bbs"
database_id = "f6607070-7f3b-4a9b-95a2-40ff67283362"

[triggers]
crons = ["0 0 * * *"]

[placement]
mode = "smart"

[[analytics_engine_datasets]]
binding = "logdb"

[ai]
binding = "AI"